# Generated by Django 4.1.12 on 2023-10-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInTime', models.IntegerField()),
                ('checkOutTime', models.IntegerField(blank=True, null=True)),
                ('ExpectedDuration', models.IntegerField()),
                ('GPS_Location', models.CharField(max_length=60)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
    ]
