# Generated by Django 4.2.6 on 2023-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('checkInTime', models.DateTimeField()),
                ('checkOutTime', models.DateTimeField()),
                ('ExpectedDuration', models.IntegerField()),
                ('GPS_Location', models.CharField(max_length=60)),
            ],
        ),
    ]
