# Generated by Django 4.2.6 on 2023-10-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_visits'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visits',
            table='visits',
        ),
    ]
