# Generated by Django 4.2.6 on 2023-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_visits_checkouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='checkOutTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
