# Generated by Django 4.1.12 on 2023-10-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_visits_checkouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='checkInTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visits',
            name='checkOutTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
