# Generated by Django 4.2.6 on 2023-10-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_visits_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
