# Generated by Django 4.2.6 on 2023-10-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_users_id_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visits',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.users'),
        ),
    ]
