# Generated by Django 4.2.6 on 2023-10-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_visits_checkintime_alter_visits_checkouttime'),
        ('pages', '0010_remove_users_id_alter_users_username_and_more'),
    ]

    operations = [
    ]
